const data = {
  products: [
    {
      _id: '1',
      name: 'Baby Dragon',
      category: 'Pets',
      image: '/images/p1.jpg',
      price: 12729218383296780,
      countInStock: 0.000001,
      brand: 'RW',
      rating: 4.5,
      numReviews: 10,
      description: 'Cute but fierce, your best companion!',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 0.000001,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 10,
      description: 'very FREE(totally)!',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 0.000001,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 0.000001,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'slim for slim peeps not chunky peeps',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 0.000001,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'PUMA!',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 0.000001,
      brand: 'Adidas',
      rating: 4.9,
      numReviews: 15,
      description: 'For fit people only',
    },
  ],
};
export default data;